// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.4
// source: audit/audit.proto

package audit

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RawRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID      string `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Payload string `protobuf:"bytes,2,opt,name=Payload,proto3" json:"Payload,omitempty"`
}

func (x *RawRequest) Reset() {
	*x = RawRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_audit_audit_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RawRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RawRequest) ProtoMessage() {}

func (x *RawRequest) ProtoReflect() protoreflect.Message {
	mi := &file_audit_audit_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RawRequest.ProtoReflect.Descriptor instead.
func (*RawRequest) Descriptor() ([]byte, []int) {
	return file_audit_audit_proto_rawDescGZIP(), []int{0}
}

func (x *RawRequest) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

func (x *RawRequest) GetPayload() string {
	if x != nil {
		return x.Payload
	}
	return ""
}

type RawResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ok uint32 `protobuf:"varint,1,opt,name=Ok,proto3" json:"Ok,omitempty"`
}

func (x *RawResponse) Reset() {
	*x = RawResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_audit_audit_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RawResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RawResponse) ProtoMessage() {}

func (x *RawResponse) ProtoReflect() protoreflect.Message {
	mi := &file_audit_audit_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RawResponse.ProtoReflect.Descriptor instead.
func (*RawResponse) Descriptor() ([]byte, []int) {
	return file_audit_audit_proto_rawDescGZIP(), []int{1}
}

func (x *RawResponse) GetOk() uint32 {
	if x != nil {
		return x.Ok
	}
	return 0
}

var File_audit_audit_proto protoreflect.FileDescriptor

var file_audit_audit_proto_rawDesc = []byte{
	0x0a, 0x11, 0x61, 0x75, 0x64, 0x69, 0x74, 0x2f, 0x61, 0x75, 0x64, 0x69, 0x74, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x05, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x36, 0x0a, 0x0a, 0x52, 0x61,
	0x77, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x44, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x49, 0x44, 0x12, 0x18, 0x0a, 0x07, 0x50, 0x61, 0x79, 0x6c,
	0x6f, 0x61, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x50, 0x61, 0x79, 0x6c, 0x6f,
	0x61, 0x64, 0x22, 0x1d, 0x0a, 0x0b, 0x52, 0x61, 0x77, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x0e, 0x0a, 0x02, 0x4f, 0x6b, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x02, 0x4f,
	0x6b, 0x32, 0x3d, 0x0a, 0x05, 0x41, 0x75, 0x64, 0x69, 0x74, 0x12, 0x34, 0x0a, 0x09, 0x52, 0x61,
	0x77, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x12, 0x11, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e,
	0x52, 0x61, 0x77, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x12, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2e, 0x52, 0x61, 0x77, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00,
	0x42, 0x29, 0x5a, 0x27, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x73,
	0x65, 0x6d, 0x65, 0x6e, 0x6f, 0x76, 0x65, 0x6d, 0x2f, 0x70, 0x6f, 0x72, 0x74, 0x61, 0x6c, 0x2f,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x61, 0x75, 0x64, 0x69, 0x74, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_audit_audit_proto_rawDescOnce sync.Once
	file_audit_audit_proto_rawDescData = file_audit_audit_proto_rawDesc
)

func file_audit_audit_proto_rawDescGZIP() []byte {
	file_audit_audit_proto_rawDescOnce.Do(func() {
		file_audit_audit_proto_rawDescData = protoimpl.X.CompressGZIP(file_audit_audit_proto_rawDescData)
	})
	return file_audit_audit_proto_rawDescData
}

var file_audit_audit_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_audit_audit_proto_goTypes = []interface{}{
	(*RawRequest)(nil),  // 0: proto.RawRequest
	(*RawResponse)(nil), // 1: proto.RawResponse
}
var file_audit_audit_proto_depIdxs = []int32{
	0, // 0: proto.Audit.RawString:input_type -> proto.RawRequest
	1, // 1: proto.Audit.RawString:output_type -> proto.RawResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_audit_audit_proto_init() }
func file_audit_audit_proto_init() {
	if File_audit_audit_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_audit_audit_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RawRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_audit_audit_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RawResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_audit_audit_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_audit_audit_proto_goTypes,
		DependencyIndexes: file_audit_audit_proto_depIdxs,
		MessageInfos:      file_audit_audit_proto_msgTypes,
	}.Build()
	File_audit_audit_proto = out.File
	file_audit_audit_proto_rawDesc = nil
	file_audit_audit_proto_goTypes = nil
	file_audit_audit_proto_depIdxs = nil
}
