// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.4
// source: audit/audit.proto

package audit

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// UsersSearchClient is the client API for UsersSearch service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type UsersSearchClient interface {
	SearchUsers(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (*SearchResponse, error)
}

type usersSearchClient struct {
	cc grpc.ClientConnInterface
}

func NewUsersSearchClient(cc grpc.ClientConnInterface) UsersSearchClient {
	return &usersSearchClient{cc}
}

func (c *usersSearchClient) SearchUsers(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (*SearchResponse, error) {
	out := new(SearchResponse)
	err := c.cc.Invoke(ctx, "/proto.UsersSearch/SearchUsers", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UsersSearchServer is the server API for UsersSearch service.
// All implementations must embed UnimplementedUsersSearchServer
// for forward compatibility
type UsersSearchServer interface {
	SearchUsers(context.Context, *SearchRequest) (*SearchResponse, error)
	mustEmbedUnimplementedUsersSearchServer()
}

// UnimplementedUsersSearchServer must be embedded to have forward compatible implementations.
type UnimplementedUsersSearchServer struct {
}

func (UnimplementedUsersSearchServer) SearchUsers(context.Context, *SearchRequest) (*SearchResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SearchUsers not implemented")
}
func (UnimplementedUsersSearchServer) mustEmbedUnimplementedUsersSearchServer() {}

// UnsafeUsersSearchServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to UsersSearchServer will
// result in compilation errors.
type UnsafeUsersSearchServer interface {
	mustEmbedUnimplementedUsersSearchServer()
}

func RegisterUsersSearchServer(s grpc.ServiceRegistrar, srv UsersSearchServer) {
	s.RegisterService(&UsersSearch_ServiceDesc, srv)
}

func _UsersSearch_SearchUsers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UsersSearchServer).SearchUsers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.UsersSearch/SearchUsers",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UsersSearchServer).SearchUsers(ctx, req.(*SearchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// UsersSearch_ServiceDesc is the grpc.ServiceDesc for UsersSearch service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var UsersSearch_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.UsersSearch",
	HandlerType: (*UsersSearchServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SearchUsers",
			Handler:    _UsersSearch_SearchUsers_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "audit/audit.proto",
}
