basePath: /[v1]/
definitions:
  github_com_semenovem_portal_internal_rest_view.Vehicle:
    properties:
      id:
        type: integer
      name:
        type: integer
    type: object
  github_com_semenovem_portal_internal_rest_view.VehicleShort:
    properties:
      id:
        type: integer
      name:
        type: integer
    type: object
  github_com_semenovem_portal_pkg_failing.Response:
    properties:
      additional_fields:
        additionalProperties: true
        type: object
      code:
        type: integer
      message:
        type: string
      validation_errors:
        items:
          $ref: '#/definitions/github_com_semenovem_portal_pkg_failing.ValidationError'
        type: array
    type: object
  github_com_semenovem_portal_pkg_failing.ValidationError:
    properties:
      message:
        type: string
      path:
        type: string
    type: object
  internal_rest_controller_auth.loginForm:
    properties:
      device_id:
        type: string
      login:
        type: string
      password:
        type: string
    required:
    - login
    - password
    type: object
  internal_rest_controller_auth.loginResponse:
    properties:
      access_token:
        type: string
      refresh_token:
        description: TODO для разработки
        type: string
      user_id:
        type: integer
    type: object
  internal_rest_controller_auth.onetimeAuthForm:
    properties:
      user_id:
        type: integer
    required:
    - user_id
    type: object
  internal_rest_controller_auth.onetimeAuthResponse:
    properties:
      entry_id:
        type: string
      uri:
        type: string
    type: object
  internal_rest_controller_auth.refreshResponse:
    properties:
      access_token:
        type: string
      refresh_token:
        description: TODO для разработки
        type: string
    type: object
  internal_rest_controller_vehicle.ListResponse:
    properties:
      items:
        items:
          $ref: '#/definitions/github_com_semenovem_portal_internal_rest_view.VehicleShort'
        type: array
      total:
        type: integer
    type: object
host: localhost:8080
info:
  contact:
    email: semenovem@gmail.com
    name: API Support
    url: http://www.swagger.io/support
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: portal API
  version: "1.0"
paths:
  /auth/login:
    post:
      parameters:
      - description: Логин/пароль
        in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/internal_rest_controller_auth.loginForm'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/internal_rest_controller_auth.loginResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/github_com_semenovem_portal_pkg_failing.Response'
      security:
      - ApiKeyAuth: []
      summary: Авторизация пользователя
      tags:
      - auth
  /auth/logout:
    post:
      parameters:
      - description: refresh токен
        in: header
        name: refresh-token
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/internal_rest_controller_auth.loginResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/github_com_semenovem_portal_pkg_failing.Response'
      security:
      - ApiKeyAuth: []
      summary: Выход из авторизованной сессии пользователя
      tags:
      - auth
  /auth/onetime:
    post:
      parameters:
      - description: данные для создания сессии
        in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/internal_rest_controller_auth.onetimeAuthForm'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/internal_rest_controller_auth.onetimeAuthResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/github_com_semenovem_portal_pkg_failing.Response'
      security:
      - ApiKeyAuth: []
      summary: Создание ссылки для одноразовой авторизации
      tags:
      - auth
  /auth/onetime/:entry_id:
    post:
      parameters:
      - description: id сессии авторизации
        in: path
        name: session_id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/internal_rest_controller_auth.loginResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/github_com_semenovem_portal_pkg_failing.Response'
      security:
      - ApiKeyAuth: []
      summary: Логин по одноразовой ссылке
      tags:
      - auth
  /auth/refresh:
    post:
      parameters:
      - description: refresh токен
        in: header
        name: refresh-token
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/internal_rest_controller_auth.refreshResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/github_com_semenovem_portal_pkg_failing.Response'
      security:
      - ApiKeyAuth: []
      summary: Обновление токена авторизации
      tags:
      - auth
  /vehicles:
    get:
      parameters:
      - in: query
        name: end_time
        type: string
      - in: query
        maximum: 100
        name: limit
        type: integer
      - in: query
        name: offset
        type: integer
      - collectionFormat: csv
        in: query
        items:
          type: string
        name: slug[]
        type: array
      - in: query
        name: start_time
        type: string
      - collectionFormat: csv
        in: query
        items:
          type: string
        name: user_id[]
        type: array
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/internal_rest_controller_vehicle.ListResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/github_com_semenovem_portal_pkg_failing.Response'
      security:
      - ApiKeyAuth: []
      summary: Ищет автомобили по фильтру
      tags:
      - vehicles
  /vehicles/:vehicle_id:
    get:
      parameters:
      - description: ID автомобиля
        in: path
        name: vehicle_id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/github_com_semenovem_portal_internal_rest_view.Vehicle'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/github_com_semenovem_portal_pkg_failing.Response'
      security:
      - ApiKeyAuth: []
      summary: Получает данные автомобиля по ID
      tags:
      - vehicles
    post:
      parameters:
      - description: ID автомобиля
        in: path
        name: vehicle_id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "204":
          description: no content
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/github_com_semenovem_portal_pkg_failing.Response'
      security:
      - ApiKeyAuth: []
      summary: Удаляет автомобиль
      tags:
      - vehicles
    put:
      parameters:
      - description: ID автомобиля
        in: path
        name: vehicle_id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/github_com_semenovem_portal_internal_rest_view.Vehicle'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/github_com_semenovem_portal_pkg_failing.Response'
      security:
      - ApiKeyAuth: []
      summary: Обновляет данные автомобиля
      tags:
      - vehicles
securityDefinitions:
  ApiKeyAuth:
    description: Description for what is this security definition being used
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
